fix: duplicate variable on observation
ivanwilliammd/satusehat-integration pull request #114
Opened 2024-12-19 04:13 UTC by AlulCode45

2024-12-23 15:24 UTC, ivanwilliammd commented
1. Untuk MedicationRequest addMedicationCode saya tidak setuju dibuat Medication/ --> berdasarkan update terbaru kemenkes, sistem pengiriman Medication didalam contained MedicationRequest, dan tidak boleh mengandung prefix Medication/
2. Untuk observation sudah ok

silakan perbaiki pull requestnya dahulu dan nanti akan saya merge

2024-12-23 15:26 UTC, AlulCode45 commented
### 2) Bug on medication request
explanation: in documentation satu sehat on reference using format 'Medication/{reference_id}'. But on this code only using reference_id

```php
public function setMedicationReference($reference, $display)
    {
        $this->medication_request['medicationReference']['reference'] = $reference;
        $this->medication_request['medicationReference']['display'] = $display;
    }
```

Fix Code:
```php
public function setMedicationReference($reference, $display)
    {
        $this->medication_request['medicationReference']['reference'] = 'Medication/' . $reference;
        $this->medication_request['medicationReference']['display'] = $display;
    }
```

2024-12-23 15:26 UTC, ivanwilliammd requested changes
1. Untuk MedicationRequest addMedicationCode saya tidak setuju dibuat Medication/ --> berdasarkan update terbaru kemenkes, sistem pengiriman Medication didalam contained MedicationRequest, dan tidak boleh mengandung prefix Medication/
2. Untuk observation sudah ok

silakan perbaiki pull requestnya dahulu dan nanti akan saya merge

2024-12-23 15:26 UTC, ivanwilliammd commented on src/FHIR/MedicationRequest.php
Untuk MedicationRequest addMedicationCode saya tidak setuju dibuat Medication/ --> berdasarkan update terbaru kemenkes, sistem pengiriman Medication didalam contained MedicationRequest, dan tidak boleh mengandung prefix Medication/

2024-12-23 15:28 UTC, ivanwilliammd commented on src/FHIR/MedicationRequest.php
https://www.postman.com/satusehat/satusehat-public/request/30206597-6199de87-05b4-466a-b5bd-a2098bbc98d4?tab=body

2024-12-23 15:28 UTC, AlulCode45 commented on src/FHIR/MedicationRequest.php
Saya mengalami error ketika mengirimkan medication request terkait reference

```text
array:2 [▼ // app\Models\ResepModels.php:37
  0 => 400
  1 => {#3216 ▼
    +"resourceType": "OperationOutcome"
    +"text": {#3221 ▶}
    +"issue": array:3 [▼
      0 => {#2899 ▼
        +"severity": "error"
        +"code": "value"
        +"details": {#3209 ▼
          +"text": "medicationReference has to refer to Medication (Rule Number: 10135)"
        }
        +"expression": array:1 [▼
          0 => "MedicationRequest.medicationReference"
        ]
      }
      1 => {#3202 ▼
        +"severity": "error"
        +"code": "value"
        +"details": {#3219 ▼
          +"text": "Wrong reference format: bcac4b8e-a76f-4132-af2a-ef2a542b6455 (RuleNumber: 10135)"
        }
        +"expression": array:1 [▼
          0 => "MedicationRequest.medicationReference"
        ]
      }
      2 => {#3184 ▼
        +"severity": "error"
        +"code": "value"
        +"details": {#3155 ▼
          +"text": "Element not found: MedicationRequest.dispenseRequest (RuleNumber: 10453)"
        }
        +"expression": array:1 [▼
          0 => "MedicationRequest.dispenseRequest"
        ]
      }
    ]
  }
]
```

2024-12-23 15:29 UTC, AlulCode45 commented on src/FHIR/MedicationRequest.php
issue key 0 dan 1, menjelaskan format tidak sesuai

2024-12-23 15:34 UTC, AlulCode45 commented on src/FHIR/MedicationRequest.php
namun ketika saya menambahkan prefix medication sebelum reference_id tidak ada error yang muncul untuk hal tersebutnamun ketika saya menambahkan prefix medication sebelum reference_id tidak ada error yang muncul untuk hal tersebut

2024-12-23 15:39 UTC, AlulCode45 commented on src/FHIR/MedicationRequest.php
saya menggunakan acuan link API berikut
[https://www.postman.com/satusehat/satusehat-public/request/ku34cjo/medicationrequest-create?tab=body](url)

2024-12-23 15:54 UTC, AlulCode45 commented on src/FHIR/MedicationRequest.php
https://satusehat.kemkes.go.id/platform/docs/id/fhir/resources/medication-request/#medicationrequest-medicationreference

2024-12-23 15:59 UTC, closed without merging

2024-12-24 04:31 UTC, AlulCode45 commented on src/FHIR/MedicationRequest.php
baik terimakasih informasinya pak

2024-12-24 04:32 UTC, AlulCode45 commented on src/FHIR/MedicationRequest.php
namun kenapa ya bisa terjadi error seperti yang saya sampaikan tadi

2024-12-24 04:33 UTC, AlulCode45 commented on src/FHIR/MedicationRequest.php
adakah kode saya yang salah
```php

$medication = new MedicationRequest();
            $medication->addPrescriptionIdentifier("RSP-".Str::random(8));
            $medication->addPrescriptionIdentifier("RSP-".Str::random(8));

            $medication->setStatus();
            $medication->setIntent();
            $medication->addCategory();
            $medication->setSubject($pasienData->patient_id, $pasienData->nama_pasien);
            $medication->setEncounter($pasien->uuid);
            $medication->setRequester($dokter->ihs, $dokter->name);
            $medication->addNote($data['aturan_tambahan']);

            $medication->setMedicationReference($obat->reference_id, $obat->name);
            $medication->addDosageInstruction(
                intval($data['frekuensi_penggunaan_obat_per_hari']),
                $data['rute'],
                $data['timing'],
                $data['aturan_tambahan']
            );
            $medication->setSubstitution();

            $medication->json();

            [$responseCode, $response] = $medication->post();

            return [$responseCode, $response];
```

2024-12-24 20:07 UTC, ivanwilliammd commented on src/FHIR/MedicationRequest.php
silakan topik ini ditanyakan ke bagian Github Discussion / Issue