fix: Encounter & Condition bundle
ivanwilliammd/satusehat-integration pull request #27
Opened 2024-03-30 12:03 UTC by SyaefulKai

Sebelumnya metode addCondition hanya membuat conditionnya saja, tidak menambahkan referensi condition ke dalam Encounter. Sekarang condition/diagnosis sudah di referensikan di dalam Encounter.

2024-03-30 12:23 UTC, SyaefulKai commented
Wiki updatenya bisa dilihat [di sini](https://github.com/SyaefulKai/satusehat-integration/blob/wiki-update/Usage.md)

2024-03-30 12:48 UTC, ivanwilliammd requested changes
Note: setelah saya cek kembali ini sepertinya masih perlu disesuaikan kembali

Perlu diperhatikan pada saat addCondition --> $encounter->addDiagnosis juga perlu ditrigger...

Sehingga usul selain public $encounter_id, public $encounter juga perlu dideklarasi

2024-03-30 18:02 UTC, ivanwilliammd requested changes
// Menambahkan diagnosis ke encounter 
         $this->encounter->addDiagnosis($condition_uuid, $condition->condition['code']['coding'][0]['code']);

Harusnya bukan $condition_uuid saja, tetapi ada prefix urn:uuid juga

2024-03-31 01:15 UTC, ivanwilliammd approved these changes
Great job : 

Note - json_decode pada POST & PUT Encounter tunggal tidak dianjurkan
json_decode untuk squashing ke dalam komponen bundle sudah tepat dilakukan

Alasannya : karena Guzzle library HTTP dapat lgsg passing json object, dan tidak lagi menerima text (hasil json_decode)

2024-03-31 01:18 UTC, merged